version: '3.9'

services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  redis:
    restart: unless-stopped
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
  app:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DEBUG=${DEBUG}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_PARTNER_CLIENT_VERSION=${SPOTIFY_PARTNER_CLIENT_VERSION}
      - SPOTIFY_KEY_COOKIE=${SPOTIFY_KEY_COOKIE}
      - SPOTIFY_DC_COOKIE=${SPOTIFY_DC_COOKIE}
    volumes:
      - ./web/:/web
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

volumes:
  pg-data:
