version: '3.9'

services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  redis:
    restart: unless-stopped
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
  app:
    image: registry.digitalocean.com/parterre-cr/backend:latest
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    restart: always
    container_name: app
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DEBUG=${DEBUG}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_PARTNER_CLIENT_VERSION=${SPOTIFY_PARTNER_CLIENT_VERSION}
      - SPOTIFY_KEY_COOKIE=${SPOTIFY_KEY_COOKIE}
      - SPOTIFY_DC_COOKIE=${SPOTIFY_DC_COOKIE}
    volumes:
      - ./web/:/web
      - static_volume:/web/staticfiles/
    expose:
      - 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  webserver:
    image: nginx:latest
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:ro
      - static_volume:/web/staticfiles/:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - app

volumes:
  pg-data:
  static_volume:
