# Generated by Django 4.1.7 on 2023-04-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artists", "0003_trackpopularity_spotify_plays"),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spotify_url", models.URLField(max_length=256)),
                (
                    "name",
                    models.CharField(
                        blank=True, default=None, max_length=256, null=True
                    ),
                ),
                ("tracks", models.ManyToManyField(to="artists.track")),
            ],
        ),
    ]
