# Generated by Django 4.1.7 on 2023-03-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artists", "0002_track_rename_otherprofiles_profile_artist_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackpopularity",
            name="spotify_plays",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
