# Generated by Django 4.1.7 on 2023-05-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artists", "0003_trackpopularity_spotify_plays"),
    ]

    operations = [
        migrations.AddField(
            model_name="artistpopularity",
            name="monthly_listeners",
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
    ]
