# Generated by Django 4.1.7 on 2023-05-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artists", "0004_artistpopularity_monthly_listeners"),
    ]

    operations = [
        migrations.AddField(
            model_name="artistpopularity",
            name="parterre_score",
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
    ]
