# Generated by Django 4.1.7 on 2023-05-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artists", "0005_artistpopularity_parterre_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artistpopularity",
            name="parterre_score",
            field=models.FloatField(),
        ),
    ]
