# Generated by Django 4.1.7 on 2023-05-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artists", "0006_alter_artistpopularity_parterre_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="force_visible",
            field=models.BooleanField(default=False),
        ),
    ]
