# Generated by Django 4.1.13 on 2023-12-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_artist_force_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='stage_name',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
