# Generated by Django 4.1.13 on 2023-12-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0008_alter_artist_stage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackpopularity',
            name='spotify_plays',
            field=models.BigIntegerField(),
        ),
    ]
