# Generated by Django 4.1.13 on 2024-01-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0010_genre_artist_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, related_name='artists', to='artists.genre'),
        ),
    ]
