# Generated by Django 4.1.7 on 2023-03-27 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_wallet_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="artist",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="artists.artist",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="notes",
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
