# Generated by Django 4.1.7 on 2023-05-05 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("artists", "0003_trackpopularity_spotify_plays"),
        ("users", "0003_transaction_artist_alter_transaction_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("slots", models.IntegerField(default=3)),
                ("artists", models.ManyToManyField(to="artists.artist")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
