# Generated by Django 4.1.13 on 2024-05-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Venduto'), ('withdraw', 'Acquistato')], max_length=10),
        ),
    ]
