# Generated by Django 4.1.13 on 2024-05-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Venduto'), ('withdraw', 'Acquistato'), ('royalty', 'Royalty')], max_length=10),
        ),
    ]
